CREATE TABLE transport_document (ID SERIAL NOT NULL, STATUS varchar(255) NOT NULL, CONSIGNEE_COMPANY int4 NOT NULL, WASTE_HOLDER_COMPANY int4 NOT NULL, CARRIER_COMPANY int4 NOT NULL, CONSIGNEE_PERSON int4 NOT NULL, WASTE_HOLDER_PERSON int4 NOT NULL, DRIVER int4 NOT NULL, ORIGIN int4 NOT NULL, DESTINATION int4 NOT NULL, SENT_TO_MINISTRY_AT timestamp NOT NULL, CREATED_AT timestamp NOT NULL, MODIFIED_AT timestamp NOT NULL, ORDER_REFERENCE int4 NOT NULL, VEHICLE varchar(255) NOT NULL, CONSTRAINT document_pk PRIMARY KEY (ID));
CREATE TABLE person (ID SERIAL NOT NULL, name varchar(255) NOT NULL, email varchar(255) NOT NULL, phone varchar(255) NOT NULL, ADDRESS varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE company (ID SERIAL NOT NULL, BUSINESS_ID int4 NOT NULL, name varchar(255) NOT NULL, COMPANY_TYPE_ID int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE company_type (ID SERIAL NOT NULL, type varchar(255) NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE coordinate (ID SERIAL NOT NULL, LOCATION varchar(255) NOT NULL, LONGITUDE float4 NOT NULL, LATITUDE float4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE material (ID int4 NOT NULL, MATERIAL_TYPE_ID int4 NOT NULL, estimatedWeight int4 NOT NULL, actualWeight int4 NOT NULL, TRANSPORT_DOCUMENT_ID int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE material_type (ID SERIAL NOT NULL, type varchar(255) NOT NULL, PRIMARY KEY (ID));

ALTER TABLE transport_document ADD CONSTRAINT FKcompany_1 FOREIGN KEY (CONSIGNEE_COMPANY) REFERENCES company (ID);
ALTER TABLE transport_document ADD CONSTRAINT FKcompany_2 FOREIGN KEY (WASTE_HOLDER_COMPANY) REFERENCES company (ID);
ALTER TABLE transport_document ADD CONSTRAINT FKcompany_3 FOREIGN KEY (CARRIER_COMPANY) REFERENCES company (ID);

ALTER TABLE transport_document ADD CONSTRAINT FKcompany_4 FOREIGN KEY (CONSIGNEE_PERSON) REFERENCES person (ID);
ALTER TABLE transport_document ADD CONSTRAINT FKcompany_5 FOREIGN KEY (WASTE_HOLDER_PERSON) REFERENCES person (ID);
ALTER TABLE transport_document ADD CONSTRAINT FKcompany_6 FOREIGN KEY (DRIVER) REFERENCES person (ID);

ALTER TABLE transport_document ADD CONSTRAINT FKcompany_7 FOREIGN KEY (ORIGIN) REFERENCES coordinate (ID);
ALTER TABLE transport_document ADD CONSTRAINT FKcompany_8 FOREIGN KEY (DESTINATION) REFERENCES coordinate (ID);

ALTER TABLE company ADD CONSTRAINT FKcompany_9 FOREIGN KEY (COMPANY_TYPE_ID) REFERENCES company_type (ID);

ALTER TABLE material ADD CONSTRAINT FKcompany_10 FOREIGN KEY (MATERIAL_TYPE_ID) REFERENCES material_type (ID);
ALTER TABLE material ADD CONSTRAINT FKcompany_11 FOREIGN KEY (TRANSPORT_DOCUMENT_ID) REFERENCES transport_document (ID);